
import * as React from 'react';
import Layout from './Layout';
import KanbanBoard from './KanbanBoard';
import { Task, TaskStatus, Notification, Priority } from './types';
import { INITIAL_TASKS, TEAM_MEMBERS, CURRENT_USER, INITIAL_NOTIFICATIONS } from './constants';
import { getProjectInsights, generateTaskDescription } from './geminiService';

const App: React.FC = () => {
  const [tasks, setTasks] = React.useState<Task[]>(INITIAL_TASKS);
  const [notifications, setNotifications] = React.useState<Notification[]>(INITIAL_NOTIFICATIONS);
  const [activeView, setActiveView] = React.useState<string>('board');
  const [isModalOpen, setModalOpen] = React.useState(false);
  const [isInsightsLoading, setInsightsLoading] = React.useState(false);
  const [insights, setInsights] = React.useState<any>(null);
  
  const [newTask, setNewTask] = React.useState<Partial<Task>>({
    title: '',
    description: '',
    status: 'todo',
    priority: 'medium',
    assigneeId: CURRENT_USER.id,
    dueDate: new Date().toISOString().split('T')[0],
    tags: []
  });

  const fetchInsights = async () => {
    setInsightsLoading(true);
    const data = await getProjectInsights(tasks);
    setInsights(data);
    setInsightsLoading(false);
    setActiveView('insights');
  };

  const handleUpdateTaskStatus = (taskId: string, newStatus: TaskStatus) => {
    setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status: newStatus } : t));
    
    const movedTask = tasks.find(t => t.id === taskId);
    if (movedTask) {
      const newNotif: Notification = {
        id: `n-${Date.now()}`,
        title: 'Task Status Updated',
        message: `${movedTask.title} moved to ${newStatus}`,
        time: 'Just now',
        read: false,
        type: 'info'
      };
      setNotifications(prev => [newNotif, ...prev]);
    }
  };

  const handleAddTask = () => {
    if (!newTask.title) return;
    
    const task: Task = {
      id: `t-${Date.now()}`,
      title: newTask.title || '',
      description: newTask.description || '',
      status: newTask.status as TaskStatus,
      priority: newTask.priority as Priority,
      assigneeId: newTask.assigneeId || CURRENT_USER.id,
      dueDate: newTask.dueDate || '',
      tags: newTask.tags || ['New']
    };

    setTasks(prev => [task, ...prev]);
    setModalOpen(false);
    setNewTask({
      title: '',
      description: '',
      status: 'todo',
      priority: 'medium',
      assigneeId: CURRENT_USER.id,
      dueDate: new Date().toISOString().split('T')[0],
      tags: []
    });
  };

  const autoGenerateDescription = async () => {
    if (!newTask.title) return;
    const desc = await generateTaskDescription(newTask.title);
    setNewTask(prev => ({ ...prev, description: desc }));
  };

  const renderContent = () => {
    switch (activeView) {
      case 'board':
        return (
          <KanbanBoard 
            tasks={tasks} 
            updateTaskStatus={handleUpdateTaskStatus}
            onAddTask={(status) => {
              setNewTask(prev => ({ ...prev, status }));
              setModalOpen(true);
            }}
          />
        );
      case 'team':
        return (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {TEAM_MEMBERS.map(member => (
              <div key={member.id} className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex items-center gap-4">
                <img src={member.avatar} className="w-16 h-16 rounded-2xl object-cover ring-4 ring-slate-50" alt={member.name} />
                <div>
                  <h3 className="font-bold text-slate-800">{member.name}</h3>
                  <p className="text-xs text-slate-500">{member.email}</p>
                  <div className="flex items-center gap-2 mt-2">
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-indigo-50 text-indigo-600 border border-indigo-100 uppercase">{member.role}</span>
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-600 border border-emerald-100 uppercase">{member.plan}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        );
      case 'insights':
        return (
          <div className="max-w-4xl mx-auto space-y-8">
            {!insights && !isInsightsLoading && (
              <div className="bg-white p-12 rounded-3xl border border-slate-200 text-center shadow-sm">
                <div className="bg-indigo-50 w-20 h-20 rounded-3xl flex items-center justify-center mx-auto mb-6">
                  <i className="fa-solid fa-wand-magic-sparkles text-indigo-600 text-3xl"></i>
                </div>
                <h3 className="text-2xl font-bold text-slate-800 mb-2">Smart Project Insights</h3>
                <p className="text-slate-500 max-w-md mx-auto mb-8">Let Gemini analyze your current tasks, team workload, and deadlines to provide strategic recommendations.</p>
                <button 
                  onClick={fetchInsights}
                  className="bg-indigo-600 text-white px-8 py-3 rounded-2xl font-semibold hover:bg-indigo-700 transition-all flex items-center gap-2 mx-auto"
                >
                  {isInsightsLoading ? <i className="fa-solid fa-spinner fa-spin"></i> : <i className="fa-solid fa-bolt"></i>}
                  Run AI Analysis
                </button>
              </div>
            )}

            {isInsightsLoading && (
              <div className="text-center py-20">
                <div className="inline-block relative">
                  <div className="w-16 h-16 border-4 border-indigo-100 border-t-indigo-600 rounded-full animate-spin mx-auto"></div>
                </div>
                <p className="mt-4 text-slate-500 font-medium animate-pulse">Scanning project metadata and generating insights...</p>
              </div>
            )}

            {insights && (
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                    <p className="text-slate-500 text-sm font-medium mb-1">Health Score</p>
                    <div className="flex items-end gap-2">
                      <span className="text-4xl font-bold text-indigo-600">{insights.healthScore}%</span>
                    </div>
                  </div>
                  <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm md:col-span-2">
                    <p className="text-slate-500 text-sm font-medium mb-1">Status Summary</p>
                    <p className="text-slate-700 leading-relaxed">{insights.summary}</p>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="bg-rose-50 p-6 rounded-2xl border border-rose-100">
                    <h4 className="font-bold text-rose-800 mb-4 flex items-center gap-2">
                      <i className="fa-solid fa-triangle-exclamation"></i> Identified Risks
                    </h4>
                    <ul className="space-y-3">
                      {insights.risks.map((risk: string, i: number) => (
                        <li key={i} className="text-sm text-rose-700 flex gap-3">
                          <span className="w-5 h-5 bg-rose-200 text-rose-800 rounded-full flex items-center justify-center shrink-0 font-bold text-[10px]">{i+1}</span>
                          {risk}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div className="bg-indigo-50 p-6 rounded-2xl border border-indigo-100">
                    <h4 className="font-bold text-indigo-800 mb-4 flex items-center gap-2">
                      <i className="fa-solid fa-lightbulb"></i> Recommendations
                    </h4>
                    <ul className="space-y-3">
                      {insights.recommendations.map((rec: string, i: number) => (
                        <li key={i} className="text-sm text-indigo-700 flex gap-3">
                          <span className="w-5 h-5 bg-indigo-200 text-indigo-800 rounded-full flex items-center justify-center shrink-0 font-bold text-[10px]">{i+1}</span>
                          {rec}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
                
                <button 
                  onClick={() => setInsights(null)}
                  className="text-slate-400 hover:text-slate-600 text-sm flex items-center gap-2"
                >
                  <i className="fa-solid fa-rotate"></i> Recalculate Insights
                </button>
              </div>
            )}
          </div>
        );
      case 'list':
        return (
          <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden">
             <table className="w-full text-left">
               <thead className="bg-slate-50 border-b border-slate-200">
                 <tr>
                   <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase">Task Name</th>
                   <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase">Status</th>
                   <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase">Priority</th>
                   <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase">Assignee</th>
                   <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase">Due Date</th>
                 </tr>
               </thead>
               <tbody className="divide-y divide-slate-100">
                 {tasks.map(task => (
                   <tr key={task.id} className="hover:bg-slate-50 transition-colors cursor-pointer">
                     <td className="px-6 py-4">
                       <p className="font-semibold text-slate-800">{task.title}</p>
                       <p className="text-xs text-slate-400">{task.tags.join(', ')}</p>
                     </td>
                     <td className="px-6 py-4">
                       <span className={`px-2 py-1 rounded-full text-[10px] font-bold uppercase ${
                         task.status === 'done' ? 'bg-emerald-100 text-emerald-700' :
                         task.status === 'in-progress' ? 'bg-indigo-100 text-indigo-700' :
                         task.status === 'review' ? 'bg-amber-100 text-amber-700' :
                         'bg-slate-100 text-slate-700'
                       }`}>
                         {task.status.replace('-', ' ')}
                       </span>
                     </td>
                     <td className="px-6 py-4">
                       <span className="text-xs font-medium text-slate-600 capitalize">{task.priority}</span>
                     </td>
                     <td className="px-6 py-4">
                        <div className="flex items-center gap-2">
                           <img src={`https://picsum.photos/seed/${task.assigneeId}/50`} className="w-6 h-6 rounded-full" alt="av" />
                           <span className="text-xs text-slate-600">
                             {TEAM_MEMBERS.find(m => m.id === task.assigneeId)?.name}
                           </span>
                        </div>
                     </td>
                     <td className="px-6 py-4 text-xs text-slate-500">{task.dueDate}</td>
                   </tr>
                 ))}
               </tbody>
             </table>
          </div>
        );
      default:
        return <div>View under construction</div>;
    }
  };

  return (
    <Layout 
      user={CURRENT_USER} 
      notifications={notifications} 
      activeView={activeView}
      setActiveView={setActiveView}
      onLogout={() => alert('Logout simulation')}
    >
      {renderContent()}

      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm">
          <div className="bg-white w-full max-w-lg rounded-3xl shadow-2xl p-8 animate-in fade-in zoom-in duration-200">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-2xl font-bold text-slate-800">Create New Task</h3>
              <button onClick={() => setModalOpen(false)} className="text-slate-400 hover:text-slate-600">
                <i className="fa-solid fa-xmark text-xl"></i>
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Task Title</label>
                <div className="relative">
                  <input 
                    type="text" 
                    placeholder="Enter task name..."
                    className="w-full px-4 py-3 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all"
                    value={newTask.title}
                    onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                  />
                  <button 
                    onClick={autoGenerateDescription}
                    title="Generate description using AI"
                    className="absolute right-2 top-2 h-8 w-8 bg-indigo-50 text-indigo-600 rounded-lg flex items-center justify-center hover:bg-indigo-100"
                  >
                    <i className="fa-solid fa-wand-magic-sparkles text-xs"></i>
                  </button>
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Description</label>
                <textarea 
                  rows={4}
                  placeholder="Details about this task..."
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all text-sm resize-none"
                  value={newTask.description}
                  onChange={(e) => setNewTask({ ...newTask, description: e.target.value })}
                ></textarea>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-1">Priority</label>
                  <select 
                    className="w-full px-4 py-3 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 text-sm"
                    value={newTask.priority}
                    onChange={(e) => setNewTask({ ...newTask, priority: e.target.value as Priority })}
                  >
                    <option value="low">Low</option>
                    <option value="medium">Medium</option>
                    <option value="high">High</option>
                    <option value="urgent">Urgent</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-1">Due Date</label>
                  <input 
                    type="date"
                    className="w-full px-4 py-3 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 text-sm"
                    value={newTask.dueDate}
                    onChange={(e) => setNewTask({ ...newTask, dueDate: e.target.value })}
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Assignee</label>
                <div className="flex flex-wrap gap-2">
                  {TEAM_MEMBERS.map(member => (
                    <button
                      key={member.id}
                      onClick={() => setNewTask({ ...newTask, assigneeId: member.id })}
                      className={`flex items-center gap-2 p-1.5 rounded-xl border transition-all ${newTask.assigneeId === member.id ? 'bg-indigo-50 border-indigo-200 ring-2 ring-indigo-500/20' : 'bg-white border-slate-100 hover:border-slate-300'}`}
                    >
                      <img src={member.avatar} className="w-6 h-6 rounded-lg" alt={member.name} />
                      <span className="text-xs font-medium pr-2">{member.name}</span>
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <div className="mt-8 flex gap-3">
              <button 
                onClick={() => setModalOpen(false)}
                className="flex-1 px-6 py-3 rounded-2xl font-bold text-slate-600 hover:bg-slate-100 transition-all"
              >
                Cancel
              </button>
              <button 
                onClick={handleAddTask}
                className="flex-[2] bg-indigo-600 text-white px-6 py-3 rounded-2xl font-bold hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200"
              >
                Create Task
              </button>
            </div>
          </div>
        </div>
      )}
    </Layout>
  );
};

export default App;
